"""Copy the finished deliverables from data/ into the tracked paper_3_audit/.

A symlink would not work: `data/` is git-ignored, so a symlinked `paper_3_audit/`
would commit a pointer into an untracked tree and the deliverables would be
unreachable from a fresh clone. Plain copies are what get committed.

`*.parquet` is git-ignored globally, so only `.md` and `.csv` are published; the
parquet intermediates stay in `data/paper_3_audit/` as the working record.
"""
from __future__ import annotations

import logging
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from src.paper_3._utils import OUT_DIR, PROJECT_ROOT, PUBLISH_DIR

logger = logging.getLogger(__name__)

#: Deliverables, in the order a reader should meet them.
PUBLISHED = (
    "GAP_MATRIX.md",
    "GAP_MATRIX.csv",
    "GAP_MATRIX_EXPLORATORY_UNVALIDATED.md",
    "GAP_MATRIX_EXPLORATORY_UNVALIDATED.csv",
    "PAPER_EXTRACTION.csv",
    "NOVELTY_STATEMENT.md",
    # The L-series: how the manuscript positions itself against the literature.
    "LITERATURE_MATRIX.md",
    "LITERATURE_MATRIX.csv",
    "LITERATURE_MATRIX_EXPLORATORY_UNVALIDATED.md",
    "LITERATURE_MATRIX_EXPLORATORY_UNVALIDATED.csv",
    "SECTION_7_8_STUB.md",
    "SLICE_SCREENING.csv",
    "SLICE_DENOMINATORS.csv",
    "CORPUS_COVERAGE.csv",
    "REFERENCES_CANDIDATES.csv",
    # Provenance: what the numbers were produced from, and how well retrieval
    # was shown to work. A matrix without these is not auditable.
    "RETRIEVAL_MANIFEST.md",
    "ACCEPTANCE_GATE.md",
    "CONTROL_WORKSHEET.csv",
    "POSITIVE_CONTROL.csv",
    "CALIBRATION_REPORT.md",
    "RUN_MANIFEST.md",
    # Own-data evidence package and the assembled manuscript (2026-09-18).
    "OWN_EVIDENCE.csv",
    "ARTICLE_THESES.csv",
    "REFERENCES.csv",
    "REFERENCES.md",
    "paper1_manuscript_en.md", "paper1_manuscript_en.docx",
    "paper1_manuscript_uk.md", "paper1_manuscript_uk.docx",
    "paper2_manuscript_en.md", "paper2_manuscript_en.docx",
    "paper2_manuscript_uk.md", "paper2_manuscript_uk.docx",
    "PAPER1_OPEN_ITEMS.md", "PAPER2_OPEN_ITEMS.md",
    "swot_dnipro_snapshot/SNAPSHOT_MANIFEST.json",
    "harvest/harvest_report.md",
    "harvest/harvest_provenance.json",
)

_HEADER = (
    "<!-- Generated by src.paper_3 · run {run_id} · commit {commit} · {ts}\n"
    "     Source of record: data/paper_3_audit/{name}. Do not edit by hand —\n"
    "     re-run `python -m src.paper_3.cli --step publish` instead. -->\n"
)


def git_commit() -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                             cwd=str(PROJECT_ROOT), capture_output=True,
                             text=True, timeout=10)
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def run(out_dir: Path | None = None, publish_dir: Path | None = None,
        run_id: str = "") -> list[Path]:
    """Copy every available deliverable. Missing ones are reported, not fatal."""
    source = Path(out_dir) if out_dir else OUT_DIR
    target = Path(publish_dir) if publish_dir else PUBLISH_DIR
    target.mkdir(parents=True, exist_ok=True)

    commit = git_commit()
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    published: list[Path] = []
    missing: list[str] = []

    for rel in PUBLISHED:
        src = source / rel
        if not src.exists():
            missing.append(rel)
            continue
        dst = target / Path(rel).name
        if src.suffix == ".md":
            header = _HEADER.format(run_id=run_id or "unset", commit=commit,
                                    ts=ts, name=rel)
            dst.write_text(header + src.read_text(encoding="utf-8"), encoding="utf-8")
        else:
            shutil.copy2(src, dst)
        published.append(dst)
        logger.info("published %s", dst.name)

    if missing:
        logger.warning("not published (not produced yet): %s", ", ".join(missing))
    return published
