"""Rebase revisions.yaml on a newer publication bundle: every entry whose anchor no longer
matches is moved to `superseded_by_floodstate_eo` when its revised text (or the anchor's
replacement) is already present, and reported otherwise. Also writes
_work/revisions_for_template.md: where each remaining entry lands in manuscript_template.md
(the placeholder-carrying source that floodstate-eo edits)."""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

from tools.paper3_audit.config import OUT_DIR, PUB_DIR, WORK_DIR
from tools.paper3_audit.revise import REVISIONS_YAML, _find_once

PH = re.compile(r"\{\{[^}]*\}\}")


def _present(text: str, needle: str) -> bool:
    try:
        _find_once(text, needle)
        return True
    except ValueError as exc:
        return str(exc).startswith("not unique")


def rebase(commit: str, texts: dict[str, str]) -> tuple[list[dict], list[dict], list[dict]]:
    doc = yaml.safe_load(REVISIONS_YAML.read_text(encoding="utf-8"))
    keep, superseded, broken = [], list(doc.get("superseded_by_floodstate_eo", [])), []
    for e in doc["revisions"]:
        text = texts[e.get("file", "manuscript.md")]
        anchor = e.get("original") or e.get("insert_after")
        if _present(text, anchor):
            keep.append(e); continue
        # anchor gone: is the change already in the bundle?
        probe = e["revised"][:120] if "original" in e else e["revised"][:80]
        if _present(text, probe):
            superseded.append({"id": e["id"], "section": e["section"],
                               "superseded_by": f"floodstate-eo {commit} applied an equivalent change (AUDIT_ACTIONS round 2)"})
        else:
            broken.append(e)
    return keep, superseded, broken


def template_map(entries: list[dict]) -> str:
    tpl = (PUB_DIR / "manuscript_template.md").read_text(encoding="utf-8")
    lines = tpl.split("\n")

    def line_of(pos: int) -> int:
        return tpl.count("\n", 0, pos) + 1

    out = ["# Where each remaining audit revision lands in manuscript_template.md", "",
           "Generated by tools/paper3_audit/rebase.py. `template span` = the lines of manuscript_template.md that hold the "
           "original sentence (located by its first and last words, placeholders ignored). Entries marked *placeholders* "
           "contain `{{…}}` cells inside the span: re-insert the placeholders, never the printed numbers.", "",
           "| id | type | section | template lines | placeholders in span | refs |", "|---|---|---|---|---|---|"]
    detail = []
    for e in entries:
        if e.get("file", "manuscript.md") != "manuscript.md":
            out.append(f"| {e['id']} | {e['change_type']} | {e['section']} | (captions.md) | — | {', '.join(e.get('refs') or [])} |")
            continue
        anchor = e.get("original") or e.get("insert_after")
        words = anchor.split()
        head, tail = " ".join(words[:6]), " ".join(words[-6:])
        span, n_ph = "not located (numbers or reflowed text — search by the reason column)", "?"
        try:
            a, _ = _find_once(tpl, head)
            _, b = _find_once(tpl[a:], tail)
            seg = tpl[a:a + b]
            span, n_ph = f"L{line_of(a)}–L{line_of(a + b)}", str(len(PH.findall(seg)))
        except ValueError:
            pass
        out.append(f"| {e['id']} | {e['change_type']} | {e['section']} | {span} | {n_ph} | {', '.join(e.get('refs') or [])} |")
        detail += [f"### {e['id']} — {e['section']} ({span}; placeholders {n_ph})", "", f"**Reason.** {e['reason']}", "",
                   ("**Replace:**" if "original" in e else "**Insert after:**"), "", "> " + " ".join(anchor.split()), "",
                   "**With:**", "", "> " + " ".join(e["revised"].split()), ""]
    return "\n".join(out + [""] + detail) + "\n"


def run(commit: str) -> int:
    texts = {f: (PUB_DIR / f).read_text(encoding="utf-8") for f in ("manuscript.md", "captions.md")}
    keep, superseded, broken = rebase(commit, texts)
    if broken:
        print("BROKEN (anchor gone, revised text absent):", [b["id"] for b in broken])
        for b in broken:
            print("  ", b["id"], repr((b.get("original") or b.get("insert_after"))[:100]))
    doc = {"revisions": keep, "superseded_by_floodstate_eo": superseded}
    REVISIONS_YAML.write_text(yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, width=110), encoding="utf-8")
    (WORK_DIR / "revisions_for_template.md").write_text(template_map(keep), encoding="utf-8")
    print(f"rebase on {commit}: kept {len(keep)}, superseded total {len(superseded)}, broken {len(broken)}")
    return 1 if broken else 0


if __name__ == "__main__":
    sys.exit(run(sys.argv[1]))
