"""biblio http cache

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 07:49:24.057505
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('http_cache',
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("service IN ('crossref', 'openalex', 'datacite', 'unpaywall', 'url')", name=op.f('ck_http_cache_service')),
    sa.CheckConstraint('status IN (200, 404, 410)', name=op.f('ck_http_cache_status')),
    sa.PrimaryKeyConstraint('service', 'key', name=op.f('pk_http_cache')),
    schema='biblio'
    )
    op.create_index('ix_http_cache_expires_at', 'http_cache', ['expires_at'], unique=False, schema='biblio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_http_cache_expires_at', table_name='http_cache', schema='biblio')
    op.drop_table('http_cache', schema='biblio')
    # ### end Alembic commands ###
