"""project biblio evidence: research data from the per-paper folders

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 07:04:47.015349
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    for schema in ("project", "biblio", "evidence"):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('repo', sa.Text(), nullable=True),
    sa.Column('paper_label', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("project_id IN ('floodstate-eo:paper3', 'kakhovka-terrain:paper2', 'swot-dnipro:paper1', 'kakhovka-report:v1', 'article1')", name=op.f('ck_project_project_id')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project')),
    schema='project'
    )
    op.create_table('cite_key',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('paper_id', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_cite_key_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_cite_key_run_id_run')),
    sa.PrimaryKeyConstraint('project_id', 'key', name=op.f('pk_cite_key')),
    schema='biblio'
    )
    op.create_table('method_reference',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('doi_or_key', sa.Text(), nullable=False),
    sa.Column('used_for', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_method_reference_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_method_reference_run_id_run')),
    sa.PrimaryKeyConstraint('project_id', 'doi_or_key', 'used_for', name=op.f('pk_method_reference')),
    schema='biblio'
    )
    op.create_table('technical_source',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('cite_as', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_technical_source_run_id_run')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_technical_source')),
    schema='biblio'
    )
    op.create_table('verification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('cite_key', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('checked_against', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('labeler_kind', sa.Text(), nullable=False),
    sa.Column('labeler', sa.Text(), nullable=False),
    sa.CheckConstraint("labeler_kind IN ('human', 'model', 'model_assisted_external', 'rule', 'import', 'unknown')", name=op.f('ck_verification_labeler_kind')),
    sa.CheckConstraint("verdict IN ('verified', 'verified_with_notes', 'mismatch', 'unresolved')", name=op.f('ck_verification_verdict')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_verification_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification')),
    schema='biblio'
    )
    op.create_index('ix_verification_doi', 'verification', ['doi'], unique=False, schema='biblio')
    op.create_table('acquisition',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('paper_id', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("route IN ('unpaywall', 'europepmc', 'openalex', 'publisher', 'arxiv', 'wayback_oa', 'manual_upload', 'legacy_unknown')", name=op.f('ck_acquisition_route')),
    sa.CheckConstraint("status IN ('downloaded', 'duplicate', 'needs_manual', 'failed')", name=op.f('ck_acquisition_status')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_acquisition_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acquisition')),
    schema='core'
    )
    op.create_index('ix_acquisition_doi', 'acquisition', ['doi'], unique=False, schema='core')
    op.create_table('claim_evidence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('thesis_id', sa.Text(), nullable=True),
    sa.Column('atomic_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('paper_id', sa.Text(), nullable=True),
    sa.Column('cite_key', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('page', sa.Text(), nullable=True),
    sa.Column('chunk_id', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('status_rule', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("role IS NULL OR role IN ('SUPPORTS', 'CONTRASTS', 'BACKGROUND', 'COMPARATOR', 'METHOD_FROM', 'DATASET_DOCUMENTATION', 'DEFINITION', 'LIMITATION', 'NOT_RELEVANT')", name=op.f('ck_claim_evidence_role')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_claim_evidence_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_claim_evidence_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_evidence')),
    schema='evidence'
    )
    op.create_table('literature_number',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('number_id', sa.Text(), nullable=False),
    sa.Column('paper_id', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('cite_key', sa.Text(), nullable=True),
    sa.Column('quantity_name', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_raw', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('window_text', sa.Text(), nullable=True),
    sa.Column('page', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified_kind', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("verified_kind IS NULL OR verified_kind IN ('human', 'model', 'model_assisted_external', 'rule', 'import', 'unknown')", name=op.f('ck_literature_number_verified_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_literature_number_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_literature_number_run_id_run')),
    sa.PrimaryKeyConstraint('project_id', 'number_id', name=op.f('pk_literature_number')),
    schema='evidence'
    )
    op.create_table('novelty_verdict',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('denominator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('labeler_kind', sa.Text(), nullable=False),
    sa.Column('labeler', sa.Text(), nullable=False),
    sa.CheckConstraint("labeler_kind IN ('human', 'model', 'model_assisted_external', 'rule', 'import', 'unknown')", name=op.f('ck_novelty_verdict_labeler_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_novelty_verdict_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_novelty_verdict_run_id_run')),
    sa.PrimaryKeyConstraint('project_id', 'question_id', name=op.f('pk_novelty_verdict')),
    schema='evidence'
    )
    op.create_table('override',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('atomic_id', sa.Text(), nullable=False),
    sa.Column('paper_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('labeler_kind', sa.Text(), nullable=False),
    sa.Column('labeler', sa.Text(), nullable=False),
    sa.CheckConstraint("labeler_kind IN ('human', 'model', 'model_assisted_external', 'rule', 'import', 'unknown')", name=op.f('ck_override_labeler_kind')),
    sa.CheckConstraint("role IS NULL OR role IN ('SUPPORTS', 'CONTRASTS', 'BACKGROUND', 'COMPARATOR', 'METHOD_FROM', 'DATASET_DOCUMENTATION', 'DEFINITION', 'LIMITATION', 'NOT_RELEVANT')", name=op.f('ck_override_role')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_override_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_override_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_override')),
    schema='evidence'
    )
    op.create_table('quote_check',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('cite_key', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('claim_use', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('checked_on', sa.Date(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('labeler_kind', sa.Text(), nullable=False),
    sa.Column('labeler', sa.Text(), nullable=False),
    sa.CheckConstraint("labeler_kind IN ('human', 'model', 'model_assisted_external', 'rule', 'import', 'unknown')", name=op.f('ck_quote_check_labeler_kind')),
    sa.CheckConstraint("verdict IN ('VERIFIED', 'FIX', 'WORDING', 'OPEN')", name=op.f('ck_quote_check_verdict')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_quote_check_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_quote_check_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_check')),
    schema='evidence'
    )
    op.create_table('screening_label',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('subject_kind', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('paper_id', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('role_raw', sa.Text(), nullable=True),
    sa.Column('relevance', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('prompt_sha256', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('labeler_kind', sa.Text(), nullable=False),
    sa.Column('labeler', sa.Text(), nullable=False),
    sa.CheckConstraint("labeler_kind IN ('human', 'model', 'model_assisted_external', 'rule', 'import', 'unknown')", name=op.f('ck_screening_label_labeler_kind')),
    sa.CheckConstraint("relevance IN ('RELEVANT', 'PARTIALLY_RELEVANT', 'NOT_RELEVANT', 'UNKNOWN')", name=op.f('ck_screening_label_relevance')),
    sa.CheckConstraint("role IS NULL OR role IN ('SUPPORTS', 'CONTRASTS', 'BACKGROUND', 'COMPARATOR', 'METHOD_FROM', 'DATASET_DOCUMENTATION', 'DEFINITION', 'LIMITATION', 'NOT_RELEVANT')", name=op.f('ck_screening_label_role')),
    sa.CheckConstraint("subject_kind IN ('thesis', 'atomic_claim', 'query')", name=op.f('ck_screening_label_subject_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_screening_label_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_screening_label_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_label')),
    schema='evidence'
    )
    op.create_index('ix_screening_label_subject', 'screening_label', ['project_id', 'subject_id'], unique=False, schema='evidence')
    op.create_table('atomic_claim',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('atomic_id', sa.Text(), nullable=False),
    sa.Column('thesis_id', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('required_roles', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('manuscript_relevance', sa.Text(), nullable=True),
    sa.Column('key_terms_primary', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('key_terms_support', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('negative_terms', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('extra_queries', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('counterevidence_queries', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('queries_version', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('labeler_kind', sa.Text(), nullable=False),
    sa.Column('labeler', sa.Text(), nullable=False),
    sa.CheckConstraint("labeler_kind IN ('human', 'model', 'model_assisted_external', 'rule', 'import', 'unknown')", name=op.f('ck_atomic_claim_labeler_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_atomic_claim_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_atomic_claim_run_id_run')),
    sa.PrimaryKeyConstraint('project_id', 'atomic_id', name=op.f('pk_atomic_claim')),
    schema='project'
    )
    op.create_table('citation_occurrence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('cite_key', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('quoted', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_citation_occurrence_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_citation_occurrence_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citation_occurrence')),
    schema='project'
    )
    op.create_table('positive_control',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('thesis_id', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=False),
    sa.Column('relevance', sa.Text(), nullable=True),
    sa.Column('expected_stage', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('source_of_seed', sa.Text(), nullable=True),
    sa.Column('manually_checked', sa.Boolean(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_positive_control_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_positive_control_run_id_run')),
    sa.PrimaryKeyConstraint('project_id', 'thesis_id', 'doi', name=op.f('pk_positive_control')),
    schema='project'
    )
    op.create_table('thesis',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('thesis_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('quantitative', sa.Text(), nullable=True),
    sa.Column('tables', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('needs', sa.Text(), nullable=True),
    sa.Column('search_queries', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('labeler_kind', sa.Text(), nullable=False),
    sa.Column('labeler', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('literature', 'report', 'article', 'novelty')", name=op.f('ck_thesis_kind')),
    sa.CheckConstraint("labeler_kind IN ('human', 'model', 'model_assisted_external', 'rule', 'import', 'unknown')", name=op.f('ck_thesis_labeler_kind')),
    sa.CheckConstraint("priority IS NULL OR priority IN ('high', 'medium', 'low')", name=op.f('ck_thesis_priority')),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.project_id'], name=op.f('fk_thesis_project_id_project')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_thesis_run_id_run')),
    sa.PrimaryKeyConstraint('project_id', 'thesis_id', name=op.f('pk_thesis')),
    schema='project'
    )
    op.create_table('thesis_ref',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('thesis_id', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('status_raw', sa.Text(), nullable=True),
    sa.CheckConstraint("relation IN ('SUPPORTED_BY', 'SUPPORTS', 'COMPARATOR', 'NEEDS_SOURCE', 'METHOD_FROM', 'METHOD', 'DATASET_DOCUMENTATION', 'BACKGROUND', 'CONTRASTS', 'CONTRASTS_WITH', 'DEFINITION', 'LIMITATION')", name=op.f('ck_thesis_ref_relation')),
    sa.CheckConstraint("status IN ('verified', 'to_verify', 'missing', 'unknown')", name=op.f('ck_thesis_ref_status')),
    sa.ForeignKeyConstraint(['project_id', 'thesis_id'], ['project.thesis.project_id', 'project.thesis.thesis_id'], name=op.f('fk_thesis_ref_project_id_thesis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'thesis_id', 'key', 'relation', name=op.f('pk_thesis_ref')),
    schema='project'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesis_ref', schema='project')
    op.drop_table('thesis', schema='project')
    op.drop_table('positive_control', schema='project')
    op.drop_table('citation_occurrence', schema='project')
    op.drop_table('atomic_claim', schema='project')
    op.drop_index('ix_screening_label_subject', table_name='screening_label', schema='evidence')
    op.drop_table('screening_label', schema='evidence')
    op.drop_table('quote_check', schema='evidence')
    op.drop_table('override', schema='evidence')
    op.drop_table('novelty_verdict', schema='evidence')
    op.drop_table('literature_number', schema='evidence')
    op.drop_table('claim_evidence', schema='evidence')
    op.drop_index('ix_acquisition_doi', table_name='acquisition', schema='core')
    op.drop_table('acquisition', schema='core')
    op.drop_index('ix_verification_doi', table_name='verification', schema='biblio')
    op.drop_table('verification', schema='biblio')
    op.drop_table('technical_source', schema='biblio')
    op.drop_table('method_reference', schema='biblio')
    op.drop_table('cite_key', schema='biblio')
    op.drop_table('project', schema='project')
    # ### end Alembic commands ###
    for schema in ("evidence", "biblio", "project"):
        op.execute(f"DROP SCHEMA IF EXISTS {schema}")
