"""ops api keys

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 06:47:35.208244
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('key_id', sa.UUID(), nullable=False),
    sa.Column('consumer', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scopes <@ ARRAY['read','llm','write','admin']::text[]", name=op.f('ck_api_key_scopes')),
    sa.PrimaryKeyConstraint('key_id', name=op.f('pk_api_key')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_key_key_hash')),
    schema='ops'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key', schema='ops')
    # ### end Alembic commands ###
