"""core and ops: paper identity and provenance

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 06:13:31.486726
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS ops")
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('git_commit', sa.Text(), nullable=True),
    sa.Column('git_dirty', sa.Boolean(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('etl', 'ingest', 'reindex', 'graph_build', 'audit', 'api_job')", name=op.f('ck_run_kind')),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'partial')", name=op.f('ck_run_status')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_run')),
    schema='ops'
    )
    op.create_table('paper',
    sa.Column('paper_id', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('openalex_id', sa.Text(), nullable=True),
    sa.Column('identity_status', sa.Text(), nullable=False),
    sa.Column('duplicate_of', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(identity_status = 'duplicate') = (duplicate_of IS NOT NULL)", name=op.f('ck_paper_duplicate_of')),
    sa.CheckConstraint("identity_status IN ('ok', 'no_doi', 'title_doi_mismatch', 'duplicate', 'not_a_paper', 'truncated_json')", name=op.f('ck_paper_identity_status')),
    sa.ForeignKeyConstraint(['duplicate_of'], ['core.paper.paper_id'], name=op.f('fk_paper_duplicate_of_paper')),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_paper_run_id_run')),
    sa.PrimaryKeyConstraint('paper_id', name=op.f('pk_paper')),
    schema='core'
    )
    op.create_index('uq_paper_doi_canonical', 'paper', ['doi'], unique=True, schema='core', postgresql_where=sa.text("doi IS NOT NULL AND identity_status <> 'duplicate'"))
    op.create_table('projection_state',
    sa.Column('store', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('item_count', sa.BigInteger(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_projection_state_run_id_run')),
    sa.PrimaryKeyConstraint('store', 'name', name=op.f('pk_projection_state')),
    schema='core'
    )
    op.create_table('source_file',
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_source_file_run_id_run')),
    sa.PrimaryKeyConstraint('sha256', 'path', name=op.f('pk_source_file')),
    schema='ops'
    )
    op.create_table('cohort_member',
    sa.Column('cohort', sa.Text(), nullable=False),
    sa.Column('paper_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['core.paper.paper_id'], name=op.f('fk_cohort_member_paper_id_paper'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_cohort_member_run_id_run')),
    sa.PrimaryKeyConstraint('cohort', 'paper_id', name=op.f('pk_cohort_member')),
    schema='core'
    )
    op.create_table('paper_alias',
    sa.Column('alias_type', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('paper_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("alias_type IN ('doi', 'doi_slug', 'doi_slug_colon', 'file_stem', 'openalex_id', 'pdf_sha256')", name=op.f('ck_paper_alias_alias_type')),
    sa.ForeignKeyConstraint(['paper_id'], ['core.paper.paper_id'], name=op.f('fk_paper_alias_paper_id_paper'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_paper_alias_run_id_run')),
    sa.PrimaryKeyConstraint('alias_type', 'alias', name=op.f('pk_paper_alias')),
    schema='core'
    )
    op.create_index('ix_paper_alias_paper_id', 'paper_alias', ['paper_id'], unique=False, schema='core')
    op.create_table('paper_file',
    sa.Column('paper_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("kind IN ('pdf', 'tei', 'paper_json', 'normalized', 'enriched', 'sodb', 'nougat_regions')", name=op.f('ck_paper_file_kind')),
    sa.CheckConstraint("status IN ('ok', 'truncated', 'duplicate_copy')", name=op.f('ck_paper_file_status')),
    sa.ForeignKeyConstraint(['paper_id'], ['core.paper.paper_id'], name=op.f('fk_paper_file_paper_id_paper'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ops.run.run_id'], name=op.f('fk_paper_file_run_id_run')),
    sa.PrimaryKeyConstraint('paper_id', 'kind', 'path', name=op.f('pk_paper_file')),
    schema='core'
    )
    op.create_index('ix_paper_file_sha256', 'paper_file', ['sha256'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_file_sha256', table_name='paper_file', schema='core')
    op.drop_table('paper_file', schema='core')
    op.drop_index('ix_paper_alias_paper_id', table_name='paper_alias', schema='core')
    op.drop_table('paper_alias', schema='core')
    op.drop_table('cohort_member', schema='core')
    op.drop_table('source_file', schema='ops')
    op.drop_table('projection_state', schema='core')
    op.drop_index('uq_paper_doi_canonical', table_name='paper', schema='core', postgresql_where=sa.text("doi IS NOT NULL AND identity_status <> 'duplicate'"))
    op.drop_table('paper', schema='core')
    op.drop_table('run', schema='ops')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS core")
    op.execute("DROP SCHEMA IF EXISTS ops")
